spring:
  application:
    name: cliente-service
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:banking_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Manchas12345.}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    exchange:
      cliente: cliente-exchange
    routing-key:
      cliente-info: cliente.info.request
      cliente-info-response: cliente.info.response
    queue:
      cliente-info-request: cliente-info-request-queue
      cliente-info-response: cliente-info-response-queue

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.banking: DEBUG
    org.springframework.web: INFO
